/**
 * Canonical API error codes returned in error responses.
 */
export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  INSUFFICIENT_INVENTORY: 'INSUFFICIENT_INVENTORY',
  RESERVATION_EXPIRED: 'RESERVATION_EXPIRED',
  RESERVATION_ALREADY_CONFIRMED: 'RESERVATION_ALREADY_CONFIRMED',
  INVALID_RESERVATION_STATE: 'INVALID_RESERVATION_STATE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** Default HTTP status for each error code. */
export const ErrorStatusMap: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 422,
  NOT_FOUND: 404,
  ITEM_NOT_FOUND: 404,
  RESERVATION_NOT_FOUND: 404,
  INSUFFICIENT_INVENTORY: 409,
  RESERVATION_EXPIRED: 409,
  RESERVATION_ALREADY_CONFIRMED: 409,
  INVALID_RESERVATION_STATE: 409,
  DATABASE_ERROR: 500,
  INTERNAL_SERVER_ERROR: 500,
};
